### ISSUE TITLE
Increase compatibility level in debian/compat to allow building debs on new Ubuntu versions

### ISSUE THREAD

**Issue by Melnorme1984** [JackSlateur/curlftpfs#7]
Since you're in the business of fixing curlftpfs bugs that the official Ubuntu distro won't, maybe you could take care of this issue as well: https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1929066.html

**Comment by JackSlateur** [comment]
Hello @Melnorme1984 
Thank you for your report, the change has been merged
